//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoeGoe_GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoeGoe_GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Clear Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cleanButton_Text {
            get {
                return ResourceManager.GetString("cleanButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cleanButton2_Text {
            get {
                return ResourceManager.GetString("cleanButton2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string deleteButton_Text {
            get {
                return ResourceManager.GetString("deleteButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emotion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string emotionButton_Text {
            get {
                return ResourceManager.GetString("emotionButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MoeGoe.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EXEPanel_Text {
            get {
                return ResourceManager.GetString("EXEPanel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HAdvancedControl_Text {
            get {
                return ResourceManager.GetString("HAdvancedControl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HModelPanel_Text {
            get {
                return ResourceManager.GetString("HModelPanel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VITS Conf に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HOpenConfig_Text {
            get {
                return ResourceManager.GetString("HOpenConfig.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HuBERT Model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HOpenHubert_Text {
            get {
                return ResourceManager.GetString("HOpenHubert.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VITS Model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HOpenModel_Text {
            get {
                return ResourceManager.GetString("HOpenModel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Origin Audio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HOpenOrigin_Text {
            get {
                return ResourceManager.GetString("HOpenOrigin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HOriginLabel_Text {
            get {
                return ResourceManager.GetString("HOriginLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HOriginLabel2_Text {
            get {
                return ResourceManager.GetString("HOriginLabel2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HTargetLabel_Text {
            get {
                return ResourceManager.GetString("HTargetLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HuBERT-VITS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string hubertPage_Text {
            get {
                return ResourceManager.GetString("hubertPage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lang Switch(1) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HVCPage1_Text {
            get {
                return ResourceManager.GetString("HVCPage1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lang Switch(2) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HVCPage2_Text {
            get {
                return ResourceManager.GetString("HVCPage2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string modelPanel_Text {
            get {
                return ResourceManager.GetString("modelPanel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Conf に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string openConfig_Text {
            get {
                return ResourceManager.GetString("openConfig.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open .exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string openEXE_Text {
            get {
                return ResourceManager.GetString("openEXE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Moel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string openModel_Text {
            get {
                return ResourceManager.GetString("openModel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original Audio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string openOrigin_Text {
            get {
                return ResourceManager.GetString("openOrigin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original Speaker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string originLabel_Text {
            get {
                return ResourceManager.GetString("originLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string paramsButton_Text {
            get {
                return ResourceManager.GetString("paramsButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string paramsButton2_Text {
            get {
                return ResourceManager.GetString("paramsButton2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string playButton_Text {
            get {
                return ResourceManager.GetString("playButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Re-Synth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string resaveButton_Text {
            get {
                return ResourceManager.GetString("resaveButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string saveButton_Text {
            get {
                return ResourceManager.GetString("saveButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string savePanel_Text {
            get {
                return ResourceManager.GetString("savePanel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speaker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string speakerLabel_Text {
            get {
                return ResourceManager.GetString("speakerLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stopButton_Text {
            get {
                return ResourceManager.GetString("stopButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Symbol に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string symbolsButton_Text {
            get {
                return ResourceManager.GetString("symbolsButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Symbol に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string symbolsButton2_Text {
            get {
                return ResourceManager.GetString("symbolsButton2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speech Synthesis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tabPage1_Text {
            get {
                return ResourceManager.GetString("tabPage1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voice Convert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tabPage2_Text {
            get {
                return ResourceManager.GetString("tabPage2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Speaker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string targetLabel_Text {
            get {
                return ResourceManager.GetString("targetLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string textLabel_Text {
            get {
                return ResourceManager.GetString("textLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MoeGoe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string this_Text {
            get {
                return ResourceManager.GetString("this.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speech Synthesis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TTSPage_Text {
            get {
                return ResourceManager.GetString("TTSPage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voice Convert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VCPage_Text {
            get {
                return ResourceManager.GetString("VCPage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VITS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string vitsPage_Text {
            get {
                return ResourceManager.GetString("vitsPage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ERM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string W2V2Model_Text {
            get {
                return ResourceManager.GetString("W2V2Model.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W2V2-VITS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string w2v2Page_Text {
            get {
                return ResourceManager.GetString("w2v2Page.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WModelPanel_Text {
            get {
                return ResourceManager.GetString("WModelPanel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VITS Conf に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WOpenConfig_Text {
            get {
                return ResourceManager.GetString("WOpenConfig.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VITS Model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WOpenModel_Text {
            get {
                return ResourceManager.GetString("WOpenModel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original Audio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WOpenOrigin_Text {
            get {
                return ResourceManager.GetString("WOpenOrigin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WOriginLabel_Text {
            get {
                return ResourceManager.GetString("WOriginLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sepaker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WSpeakerLabel_Text {
            get {
                return ResourceManager.GetString("WSpeakerLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WTargetLabel_Text {
            get {
                return ResourceManager.GetString("WTargetLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WTextLabel_Text {
            get {
                return ResourceManager.GetString("WTextLabel.Text", resourceCulture);
            }
        }
    }
}
